extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern Lights1 bob_dl_Area_1_lights;
extern Lights1 bob_dl_Area_2_lights;
extern Lights1 bob_dl_Area_3_lights;
extern Lights1 bob_dl_Area_4_lights;
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_0[4];
extern Vtx bob_dl_Level_Mesh_2_mesh_layer_1_vtx_0[4];
extern Vtx bob_dl_Level_Mesh_3_mesh_layer_1_vtx_0[4];
extern Vtx bob_dl_Level_Mesh_4_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1[];
extern Gfx bob_dl_Level_Mesh_2_mesh_layer_1[];
extern Gfx bob_dl_Level_Mesh_3_mesh_layer_1[];
extern Gfx bob_dl_Level_Mesh_4_mesh_layer_1[];
